version: "3.7"

services:
  dwspectrum-lsio:
    image: dwspectrum-lsio
    container_name: dwspectrum-lsio-test
    build: .
    restart: unless-stopped
    environment:
      - TZ=Americas/Los_Angeles
    volumes:
      - ./.mount/config:/config
      - ./.mount/media:/media
      - ./.mount/archive:/archive
    network_mode: bridge
    ports:
      - 7001:7001
